# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: tfsketch

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

archives:
  - formats: [ 'zip' ]
    files:
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

#signs:
#  - id: archive-keyless
#    cmd: cosign
#    artifacts: archive
#    signature: ${artifact}.sigstore
#    output: false
#    args:
#      - "sign-blob"
#      - "--bundle=${signature}"
#      - "${artifact}"
#      - "-y"

