---
config:
  theme: redux
  flowchart:
    diagramPadding: 5
    padding: 5
    nodeSpacing: 10
    wrappingWidth: 700
---
flowchart LR
  classDef tf-path fill:#c87de8
  classDef tf-resource-name stroke:#e7b6fc,color:#c87de8,text-align:left
  classDef tf-int-mod fill:#e7b6fc,text-align:left
  classDef tf-ext-mod fill:#7da8e8,text-align:left
  classDef tf-resource-field-name fill:#eb91c7
  account["account"]:::tf-path ---> account__acc11["resource_type.acc1_1"]:::tf-resource-name --> account__acc11_FieldName["local.another_local"]:::tf-resource-field-name
  account["account"]:::tf-path ---> account__acc12["resource_type.acc1_2"]:::tf-resource-name --> account__acc12_FieldName["&#34;${local.some_variable}-name-acc1-2&#34;"]:::tf-resource-field-name
  account["account"]:::tf-path ---> account__acc21["resource_type.acc2_1"]:::tf-resource-name --> account__acc21_FieldName["&#34;name-acc2-1&#34;"]:::tf-resource-field-name
  account["account"]:::tf-path ---> account__acc22["resource_type.acc2_2"]:::tf-resource-name --> account__acc22_FieldName["&#34;name-acc2-2&#34;"]:::tf-resource-field-name
  account --> account__accountmodulesmodule1_acc2mod11_acc2mod11["<b>module.acc2-mod1-1</b><br>./modules/module-1<br><i>for_each = local.aaa</i>"]:::tf-int-mod
  account__accountmodulesmodule1_acc2mod11_acc2mod11 --> account__accountmodulesmodule1_acc2mod11_acc2mod11__resourcenamemod21["resource_type.resource_name_mod2_1"]:::tf-resource-name --> account__accountmodulesmodule1_acc2mod11_acc2mod11__resourcenamemod21_FieldName["&#34;name-mod2-1&#34;"]:::tf-resource-field-name
  account__accountmodulesmodule1_acc2mod11_acc2mod11 --> account__accountmodulesmodule1_acc2mod11_acc2mod11__resourcenamemod22["resource_type.resource_name_mod2_2<br><i>for_each = [&#34;val1&#34;, &#34;val2&#34;]</i>"]:::tf-resource-name --> account__accountmodulesmodule1_acc2mod11_acc2mod11__resourcenamemod22_FieldName["&#34;name-mod2-2&#34;"]:::tf-resource-field-name
  account__accountmodulesmodule1_acc2mod11_acc2mod11 --> account__accountmodulesmodule1_acc2mod11_acc2mod11__resourcenamemod11["resource_type.resource_name_mod1_1"]:::tf-resource-name --> account__accountmodulesmodule1_acc2mod11_acc2mod11__resourcenamemod11_FieldName["local.another_local2"]:::tf-resource-field-name
  account__accountmodulesmodule1_acc2mod11_acc2mod11 --> account__accountmodulesmodule1_acc2mod11_acc2mod11__resourcenamemod12["resource_type.resource_name_mod1_2<br><i>for_each = local.something</i>"]:::tf-resource-name --> account__accountmodulesmodule1_acc2mod11_acc2mod11__resourcenamemod12_FieldName["&#34;${local.some_variable}-name-mod1-2&#34;"]:::tf-resource-field-name
  account --> account__accountmodulesmodule1_acc2mod12_acc2mod12["<b>module.acc2-mod1-2</b><br>./modules/module-1"]:::tf-int-mod
  account__accountmodulesmodule1_acc2mod12_acc2mod12 --> account__accountmodulesmodule1_acc2mod12_acc2mod12__resourcenamemod11["resource_type.resource_name_mod1_1"]:::tf-resource-name --> account__accountmodulesmodule1_acc2mod12_acc2mod12__resourcenamemod11_FieldName["local.another_local2"]:::tf-resource-field-name
  account__accountmodulesmodule1_acc2mod12_acc2mod12 --> account__accountmodulesmodule1_acc2mod12_acc2mod12__resourcenamemod12["resource_type.resource_name_mod1_2<br><i>for_each = local.something</i>"]:::tf-resource-name --> account__accountmodulesmodule1_acc2mod12_acc2mod12__resourcenamemod12_FieldName["&#34;${local.some_variable}-name-mod1-2&#34;"]:::tf-resource-field-name
  account__accountmodulesmodule1_acc2mod12_acc2mod12 --> account__accountmodulesmodule1_acc2mod12_acc2mod12__resourcenamemod21["resource_type.resource_name_mod2_1"]:::tf-resource-name --> account__accountmodulesmodule1_acc2mod12_acc2mod12__resourcenamemod21_FieldName["&#34;name-mod2-1&#34;"]:::tf-resource-field-name
  account__accountmodulesmodule1_acc2mod12_acc2mod12 --> account__accountmodulesmodule1_acc2mod12_acc2mod12__resourcenamemod22["resource_type.resource_name_mod2_2<br><i>for_each = [&#34;val1&#34;, &#34;val2&#34;]</i>"]:::tf-resource-name --> account__accountmodulesmodule1_acc2mod12_acc2mod12__resourcenamemod22_FieldName["&#34;name-mod2-2&#34;"]:::tf-resource-field-name
  ingress["ingress"]:::tf-path ---> ingress__ing11["resource_type.ing1_1"]:::tf-resource-name --> ingress__ing11_FieldName["&#34;name-ing1-1&#34;"]:::tf-resource-field-name
  ingress["ingress"]:::tf-path ---> ingress__ing12["resource_type.ing1_2"]:::tf-resource-name --> ingress__ing12_FieldName["&#34;name-ing1-2&#34;"]:::tf-resource-field-name
  ingress --> ingress___ing2mod21_ing2mod21["<b>module.ing2-mod2-1</b><br>external-tf-module-2\@0.1.0"]:::tf-ext-mod
  ingress___ing2mod21_ing2mod21 --> ingress___ing2mod21_ing2mod21__mod21["resource_type.mod2_1"]:::tf-resource-name --> ingress___ing2mod21_ing2mod21__mod21_FieldName["local.iam_in_external_tf_module_2"]:::tf-resource-field-name
  ingress___ing2mod21_ing2mod21 --> ingress___ing2mod21_ing2mod21__mod22["resource_type.mod2_2"]:::tf-resource-name --> ingress___ing2mod21_ing2mod21__mod22_FieldName["&#34;${local.some_variable}-iam_in_external_tf_module_2-2&#34;"]:::tf-resource-field-name
  ingress --> ingress___ing2mod22_ing2mod22["<b>module.ing2-mod2-2</b><br>external-tf-module-2\@0.1.0"]:::tf-ext-mod
  ingress___ing2mod22_ing2mod22 --> ingress___ing2mod22_ing2mod22__mod22["resource_type.mod2_2"]:::tf-resource-name --> ingress___ing2mod22_ing2mod22__mod22_FieldName["&#34;${local.some_variable}-iam_in_external_tf_module_2-2&#34;"]:::tf-resource-field-name
  ingress___ing2mod22_ing2mod22 --> ingress___ing2mod22_ing2mod22__mod21["resource_type.mod2_1"]:::tf-resource-name --> ingress___ing2mod22_ing2mod22__mod21_FieldName["local.iam_in_external_tf_module_2"]:::tf-resource-field-name
  ingress --> ingress___ing2mod4_ing2mod4["<b>module.ing2-mod4</b><br>external-tf-module-4\@0.1.0"]:::tf-ext-mod
  ingress___ing2mod4_ing2mod4 --> ingress___ing2mod4_ing2mod4__mod41["resource_type.mod4_1"]:::tf-resource-name --> ingress___ing2mod4_ing2mod4__mod41_FieldName["local.iam_in_external_tf_module_modules_4"]:::tf-resource-field-name
  ingress --> ingress___ingress___ing2mod4_ing2mod4__mod4modindirectly1_mod4modindirectly1["<b>module.ing2-mod4</b><br>external-tf-module-4\@0.1.0<br>-&gt;<br><b>module.mod4-mod-indirectly-1</b><br>../indirectly-1"]:::tf-ext-mod
  ingress___ingress___ing2mod4_ing2mod4__mod4modindirectly1_mod4modindirectly1 --> ingress___ingress___ing2mod4_ing2mod4__mod4modindirectly1_mod4modindirectly1__indirectly1["resource_type.indirectly_1<br><i>for_each = [local.something, local.something2]</i>"]:::tf-resource-name --> ingress___ingress___ing2mod4_ing2mod4__mod4modindirectly1_mod4modindirectly1__indirectly1_FieldName["&#34;indirectly-1&#34;"]:::tf-resource-field-name
