---
config:
  theme: redux
---
flowchart LR
  classDef tf-path fill:#c87de8
  classDef tf-resource-name stroke:#e7b6fc,color:#c87de8
  classDef tf-resource-name-int-mod fill:#e7b6fc
  classDef tf-resource-name-ext-mod fill:#7da8e8
  classDef tf-resource-field-name fill:#eb91c7
  account["Path: /account"]:::tf-path --> account___acc11["Resource: resource_type.acc1_1"]:::tf-resource-name --> account___acc11___FieldName["local.another_local"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___acc12["Resource: resource_type.acc1_2"]:::tf-resource-name --> account___acc12___FieldName["${local.some_variable}-name-acc1-2"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___acc21["Resource: resource_type.acc2_1"]:::tf-resource-name --> account___acc21___FieldName["name-acc2-1"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___acc22["Resource: resource_type.acc2_2"]:::tf-resource-name --> account___acc22___FieldName["name-acc2-2"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod11["Resource: module.acc2-mod1-1 > resource_type.resource_name_mod1_1"]:::tf-resource-name-int-mod --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod11___FieldName["local.another_local2"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod12["Resource: module.acc2-mod1-1 > resource_type.resource_name_mod1_2"]:::tf-resource-name-int-mod --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod12___FieldName["${local.some_variable}-name-mod1-2"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod21["Resource: module.acc2-mod1-1 > resource_type.resource_name_mod2_1"]:::tf-resource-name-int-mod --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod21___FieldName["name-mod2-1"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod22["Resource: module.acc2-mod1-1 > resource_type.resource_name_mod2_2"]:::tf-resource-name-int-mod --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod22___FieldName["name-mod2-2"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod12["Resource: module.acc2-mod1-2 > resource_type.resource_name_mod1_2"]:::tf-resource-name-int-mod --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod12___FieldName["${local.some_variable}-name-mod1-2"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod21["Resource: module.acc2-mod1-2 > resource_type.resource_name_mod2_1"]:::tf-resource-name-int-mod --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod21___FieldName["name-mod2-1"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod22["Resource: module.acc2-mod1-2 > resource_type.resource_name_mod2_2"]:::tf-resource-name-int-mod --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod22___FieldName["name-mod2-2"]:::tf-resource-field-name
  account["Path: /account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod11["Resource: module.acc2-mod1-2 > resource_type.resource_name_mod1_1"]:::tf-resource-name-int-mod --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod11___FieldName["local.another_local2"]:::tf-resource-field-name
  ingress["Path: /ingress"]:::tf-path --> ingress___ing11["Resource: resource_type.ing1_1"]:::tf-resource-name --> ingress___ing11___FieldName["name-ing1-1"]:::tf-resource-field-name
  ingress["Path: /ingress"]:::tf-path --> ingress___ing12["Resource: resource_type.ing1_2"]:::tf-resource-name --> ingress___ing12___FieldName["name-ing1-2"]:::tf-resource-field-name
  ingress["Path: /ingress"]:::tf-path --> ingress___mod___root___ing2mod22___mod22["Resource: module.ing2-mod2-2 > resource_type.mod2_2"]:::tf-resource-name-ext-mod --> ingress___mod___root___ing2mod22___mod22___FieldName["${local.some_variable}-iam_in_external_tf_module_2-2"]:::tf-resource-field-name
  ingress["Path: /ingress"]:::tf-path --> ingress___mod___root___ing2mod22___mod21["Resource: module.ing2-mod2-2 > resource_type.mod2_1"]:::tf-resource-name-ext-mod --> ingress___mod___root___ing2mod22___mod21___FieldName["local.iam_in_external_tf_module_2"]:::tf-resource-field-name
  ingress["Path: /ingress"]:::tf-path --> ingress___mod___root___ing2mod4___mod41["Resource: module.ing2-mod4 > resource_type.mod4_1"]:::tf-resource-name-ext-mod --> ingress___mod___root___ing2mod4___mod41___FieldName["local.iam_in_external_tf_module_modules_4"]:::tf-resource-field-name
  ingress["Path: /ingress"]:::tf-path --> ingress___mod___root___mod4modindirectly1___indirectly1["Resource: module.ing2-mod4 > module.mod4-mod-indirectly-1 > resource_type.indirectly_1"]:::tf-resource-name-ext-mod --> ingress___mod___root___mod4modindirectly1___indirectly1___FieldName["indirectly-1"]:::tf-resource-field-name
  ingress["Path: /ingress"]:::tf-path --> ingress___mod___root___ing2mod21___mod21["Resource: module.ing2-mod2-1 > resource_type.mod2_1"]:::tf-resource-name-ext-mod --> ingress___mod___root___ing2mod21___mod21___FieldName["local.iam_in_external_tf_module_2"]:::tf-resource-field-name
  ingress["Path: /ingress"]:::tf-path --> ingress___mod___root___ing2mod21___mod22["Resource: module.ing2-mod2-1 > resource_type.mod2_2"]:::tf-resource-name-ext-mod --> ingress___mod___root___ing2mod21___mod22___FieldName["${local.some_variable}-iam_in_external_tf_module_2-2"]:::tf-resource-field-name
