---
config:
  theme: redux
  flowchart:
    diagramPadding: 5
    padding: 5
    nodeSpacing: 10
    wrappingWidth: 700
---
flowchart LR
  classDef tf-path fill:#c87de8
  classDef tf-resource-name stroke:#e7b6fc,color:#c87de8,text-align:left
  classDef tf-int-mod fill:#e7b6fc,text-align:left
  classDef tf-ext-mod fill:#7da8e8,text-align:left
  classDef tf-resource-field-name fill:#eb91c7
  account["/account"]:::tf-path ---> account___acc11["resource_type.acc1_1"]:::tf-resource-name --> account___acc11___FieldName["local.another_local"]:::tf-resource-field-name
  account["/account"]:::tf-path ---> account___acc12["resource_type.acc1_2"]:::tf-resource-name --> account___acc12___FieldName["${local.some_variable}-name-acc1-2"]:::tf-resource-field-name
  account["/account"]:::tf-path ---> account___acc21["resource_type.acc2_1"]:::tf-resource-name --> account___acc21___FieldName["name-acc2-1"]:::tf-resource-field-name
  account["/account"]:::tf-path ---> account___acc22["resource_type.acc2_2"]:::tf-resource-name --> account___acc22___FieldName["name-acc2-2"]:::tf-resource-field-name
  account["/account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod11["<b>module.acc2-mod1-1</b><br>./modules/module-1<br><i>for_each = local.aaa</i>"]:::tf-int-mod
  account___mod___accountmodulesmodule1___acc2mod11 --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod22["resource_type.resource_name_mod2_2<br><i>for_each = [&#34;val1&#34;, &#34;val2&#34;]</i>"]:::tf-resource-name --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod22___FieldName["name-mod2-2"]:::tf-resource-field-name
  account___mod___accountmodulesmodule1___acc2mod11 --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod11["resource_type.resource_name_mod1_1"]:::tf-resource-name --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod11___FieldName["local.another_local2"]:::tf-resource-field-name
  account___mod___accountmodulesmodule1___acc2mod11 --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod12["resource_type.resource_name_mod1_2<br><i>for_each = local.something</i>"]:::tf-resource-name --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod12___FieldName["${local.some_variable}-name-mod1-2"]:::tf-resource-field-name
  account___mod___accountmodulesmodule1___acc2mod11 --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod21["resource_type.resource_name_mod2_1"]:::tf-resource-name --> account___mod___accountmodulesmodule1___acc2mod11___resourcenamemod21___FieldName["name-mod2-1"]:::tf-resource-field-name
  account["/account"]:::tf-path --> account___mod___accountmodulesmodule1___acc2mod12["<b>module.acc2-mod1-2</b><br>./modules/module-1"]:::tf-int-mod
  account___mod___accountmodulesmodule1___acc2mod12 --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod21["resource_type.resource_name_mod2_1"]:::tf-resource-name --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod21___FieldName["name-mod2-1"]:::tf-resource-field-name
  account___mod___accountmodulesmodule1___acc2mod12 --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod22["resource_type.resource_name_mod2_2<br><i>for_each = [&#34;val1&#34;, &#34;val2&#34;]</i>"]:::tf-resource-name --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod22___FieldName["name-mod2-2"]:::tf-resource-field-name
  account___mod___accountmodulesmodule1___acc2mod12 --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod11["resource_type.resource_name_mod1_1"]:::tf-resource-name --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod11___FieldName["local.another_local2"]:::tf-resource-field-name
  account___mod___accountmodulesmodule1___acc2mod12 --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod12["resource_type.resource_name_mod1_2<br><i>for_each = local.something</i>"]:::tf-resource-name --> account___mod___accountmodulesmodule1___acc2mod12___resourcenamemod12___FieldName["${local.some_variable}-name-mod1-2"]:::tf-resource-field-name
  ingress["/ingress"]:::tf-path ---> ingress___ing11["resource_type.ing1_1"]:::tf-resource-name --> ingress___ing11___FieldName["name-ing1-1"]:::tf-resource-field-name
  ingress["/ingress"]:::tf-path ---> ingress___ing12["resource_type.ing1_2"]:::tf-resource-name --> ingress___ing12___FieldName["name-ing1-2"]:::tf-resource-field-name
  ingress["/ingress"]:::tf-path --> ingress___mod___root___ing2mod22["<b>module.ing2-mod2-2</b><br>external-tf-module-2\@0.1.0"]:::tf-ext-mod
  ingress___mod___root___ing2mod22 --> ingress___mod___root___ing2mod22___mod21["resource_type.mod2_1"]:::tf-resource-name --> ingress___mod___root___ing2mod22___mod21___FieldName["local.iam_in_external_tf_module_2"]:::tf-resource-field-name
  ingress___mod___root___ing2mod22 --> ingress___mod___root___ing2mod22___mod22["resource_type.mod2_2"]:::tf-resource-name --> ingress___mod___root___ing2mod22___mod22___FieldName["${local.some_variable}-iam_in_external_tf_module_2-2"]:::tf-resource-field-name
  ingress["/ingress"]:::tf-path --> ingress___mod___root___ing2mod4["<b>module.ing2-mod4</b><br>external-tf-module-4\@0.1.0"]:::tf-ext-mod
  ingress___mod___root___ing2mod4 --> ingress___mod___root___ing2mod4___mod41["resource_type.mod4_1"]:::tf-resource-name --> ingress___mod___root___ing2mod4___mod41___FieldName["local.iam_in_external_tf_module_modules_4"]:::tf-resource-field-name
  ingress["/ingress"]:::tf-path --> ingress___mod___root___ing2mod4___mod4modindirectly1["<b>module.ing2-mod4</b><br>external-tf-module-4\@0.1.0<br>-&gt;<br><b>module.mod4-mod-indirectly-1</b><br>../indirectly-1"]:::tf-ext-mod
  ingress___mod___root___ing2mod4___mod4modindirectly1 --> ingress___mod___root___ing2mod4___mod4modindirectly1___indirectly1["resource_type.indirectly_1<br><i>for_each = [local.something, local.something2]</i>"]:::tf-resource-name --> ingress___mod___root___ing2mod4___mod4modindirectly1___indirectly1___FieldName["indirectly-1"]:::tf-resource-field-name
  ingress["/ingress"]:::tf-path --> ingress___mod___root___ing2mod21["<b>module.ing2-mod2-1</b><br>external-tf-module-2\@0.1.0"]:::tf-ext-mod
  ingress___mod___root___ing2mod21 --> ingress___mod___root___ing2mod21___mod21["resource_type.mod2_1"]:::tf-resource-name --> ingress___mod___root___ing2mod21___mod21___FieldName["local.iam_in_external_tf_module_2"]:::tf-resource-field-name
  ingress___mod___root___ing2mod21 --> ingress___mod___root___ing2mod21___mod22["resource_type.mod2_2"]:::tf-resource-name --> ingress___mod___root___ing2mod21___mod22___FieldName["${local.some_variable}-iam_in_external_tf_module_2-2"]:::tf-resource-field-name
