---
config:
  theme: redux
  flowchart:
    diagramPadding: 5
    padding: 5
    nodeSpacing: 10
    wrappingWidth: 700
---
flowchart LR
  classDef tf-path fill:#c87de8
  classDef tf-resource stroke:#e7b6fc,color:#c87de8,text-align:left
  classDef tf-int-mod fill:#e7b6fc,text-align:left
  classDef tf-ext-mod fill:#7da8e8,text-align:left
  classDef tf-name fill:#eb91c7
  p_root["."]:::tf-path
  p_root ----> r_root__nevermind1["nevermind.nevermind-1"]:::tf-resource
  r_root__nevermind1 ---> n_root__nevermind1_n["#34;name-nevermind-1#34;"]:::tf-name
  p_sub2["sub2"]:::tf-path
  p_sub2 ----> r_sub2__nevermindsub211["nevermind.nevermind-sub2-1-1"]:::tf-resource
  r_sub2__nevermindsub211 ---> n_sub2__nevermindsub211_n["#34;name-nevermind-sub2-1-1#34;"]:::tf-name
  p_sub2 ----> r_sub2__nevermindsub221["nevermind.nevermind-sub2-2-1"]:::tf-resource
  r_sub2__nevermindsub221 ---> n_sub2__nevermindsub221_n["#34;name-nevermind-sub2-2-1#34;"]:::tf-name
  p_subdir1["subdir1"]:::tf-path
  p_subdir1 ----> r_subdir1__nevermindsub11["nevermind.nevermind-sub1-1"]:::tf-resource
  r_subdir1__nevermindsub11 ---> n_subdir1__nevermindsub11_n["#34;name-nevermind-sub1-1#34;"]:::tf-name
