---
config:
  theme: redux
  flowchart:
    diagramPadding: 5
    padding: 5
    nodeSpacing: 10
    wrappingWidth: 700
---
flowchart LR
  classDef tf-path fill:#c87de8
  classDef tf-resource stroke:#e7b6fc,color:#c87de8,text-align:left
  classDef tf-int-mod fill:#e7b6fc,text-align:left
  classDef tf-ext-mod fill:#7da8e8,text-align:left
  classDef tf-name fill:#eb91c7
  p_root["."]:::tf-path
  p_root ----> r_root__typeroot11["type.root-1-1"]:::tf-resource
  r_root__typeroot11 ---> n_root__typeroot11_n["#34;name-root-1-1#34;"]:::tf-name
  p_root ----> r_root__typeroot12["type.root-1-2"]:::tf-resource
  r_root__typeroot12 ---> n_root__typeroot12_n["#34;name-root-1-2#34;"]:::tf-name
  p_root ----> r_root__typeroot13["type.root-1-3"]:::tf-resource
  r_root__typeroot13 ---> n_root__typeroot13_n["#34;name-root-1-3#34;"]:::tf-name
  p_root ----> r_root__typeroot21["type.root-2-1"]:::tf-resource
  r_root__typeroot21 ---> n_root__typeroot21_n["#34;name-root-2-1#34;"]:::tf-name
  p_root ----> r_root__typeroot22["type.root-2-2"]:::tf-resource
  r_root__typeroot22 ---> n_root__typeroot22_n["#34;name-root-2-2#34;"]:::tf-name
  p_root ----> r_root__typeroot23["type.root-2-3"]:::tf-resource
  r_root__typeroot23 ---> n_root__typeroot23_n["#34;name-root-2-3#34;"]:::tf-name
  p_sub2["sub2"]:::tf-path
  p_sub2 ----> r_sub2__typesub211["type.sub2-1-1"]:::tf-resource
  r_sub2__typesub211 ---> n_sub2__typesub211_n["#34;name-sub2-1-1#34;"]:::tf-name
  p_sub2 ----> r_sub2__typesub221["type.sub2-2-1"]:::tf-resource
  r_sub2__typesub221 ---> n_sub2__typesub221_n["#34;name-sub2-2-1#34;"]:::tf-name
  p_subdir1["subdir1"]:::tf-path
  p_subdir1 ----> r_subdir1__typetypenamesub111["type.type-name-sub1-1-1"]:::tf-resource
  r_subdir1__typetypenamesub111 ---> n_subdir1__typetypenamesub111_n["#34;name-sub1-1-1#34;"]:::tf-name
  p_subdir1 ----> r_subdir1__typetypenamesub112["type.type-name-sub1-1-2"]:::tf-resource
  r_subdir1__typetypenamesub112 ---> n_subdir1__typetypenamesub112_n["#34;name-sub1-1-2#34;"]:::tf-name
