---
config:
  theme: redux
  flowchart:
    diagramPadding: 5
    padding: 5
    nodeSpacing: 10
    wrappingWidth: 700
---
flowchart LR
  classDef tf-path fill:#c87de8
  classDef tf-resource stroke:#e7b6fc,color:#c87de8,text-align:left
  classDef tf-int-mod fill:#e7b6fc,text-align:left
  classDef tf-ext-mod fill:#7da8e8,text-align:left
  classDef tf-name fill:#eb91c7
  p_root["."]:::tf-path
  p_root ----> r_root__typerootcache1["type.root-cache-1"]:::tf-resource
  r_root__typerootcache1 ---> n_root__typerootcache1_n["#34;root-cache-1#34;"]:::tf-name
  p_root --> m_root__eks["module.eks<br>terraform-aws-modules/eks/aws(at)21.3.1"]:::tf-int-mod
  m_root__eks ---> r_root__eks__awscloudwatchloggroupthis["aws_cloudwatch_log_group.this"]:::tf-resource
  r_root__eks__awscloudwatchloggroupthis ---> n_root__eks__awscloudwatchloggroupthis_n["#34;/aws/eks/${var.name}/cluster#34;"]:::tf-name
  m_root__eks ---> r_root__eks__awsec2tagclusterprimarysecuritygroup["aws_ec2_tag.cluster_primary_security_group"]:::tf-resource
  r_root__eks__awsec2tagclusterprimarysecuritygroup ---> n_root__eks__awsec2tagclusterprimarysecuritygroup_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awseksaccessentrythis["aws_eks_access_entry.this"]:::tf-resource
  r_root__eks__awseksaccessentrythis ---> n_root__eks__awseksaccessentrythis_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awseksaccesspolicyassociationthis["aws_eks_access_policy_association.this"]:::tf-resource
  r_root__eks__awseksaccesspolicyassociationthis ---> n_root__eks__awseksaccesspolicyassociationthis_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awseksaddonbeforecompute["aws_eks_addon.before_compute"]:::tf-resource
  r_root__eks__awseksaddonbeforecompute ---> n_root__eks__awseksaddonbeforecompute_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awseksaddonthis["aws_eks_addon.this"]:::tf-resource
  r_root__eks__awseksaddonthis ---> n_root__eks__awseksaddonthis_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awseksclusterthis["aws_eks_cluster.this"]:::tf-resource
  r_root__eks__awseksclusterthis ---> n_root__eks__awseksclusterthis_n["var.name"]:::tf-name
  m_root__eks ---> r_root__eks__awseksidentityproviderconfigthis["aws_eks_identity_provider_config.this"]:::tf-resource
  r_root__eks__awseksidentityproviderconfigthis ---> n_root__eks__awseksidentityproviderconfigthis_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamopenidconnectprovideroidcprovider["aws_iam_openid_connect_provider.oidc_provider"]:::tf-resource
  r_root__eks__awsiamopenidconnectprovideroidcprovider ---> n_root__eks__awsiamopenidconnectprovideroidcprovider_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiampolicyclusterencryption["aws_iam_policy.cluster_encryption"]:::tf-resource
  r_root__eks__awsiampolicyclusterencryption ---> n_root__eks__awsiampolicyclusterencryption_n["empty!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiampolicycniipv6policy["aws_iam_policy.cni_ipv6_policy"]:::tf-resource
  r_root__eks__awsiampolicycniipv6policy ---> n_root__eks__awsiampolicycniipv6policy_n["#34;AmazonEKS_CNI_IPv6_Policy#34;"]:::tf-name
  m_root__eks ---> r_root__eks__awsiampolicycustom["aws_iam_policy.custom"]:::tf-resource
  r_root__eks__awsiampolicycustom ---> n_root__eks__awsiampolicycustom_n["empty!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamroleeksauto["aws_iam_role.eks_auto"]:::tf-resource
  r_root__eks__awsiamroleeksauto ---> n_root__eks__awsiamroleeksauto_n["empty!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamrolethis["aws_iam_role.this"]:::tf-resource
  r_root__eks__awsiamrolethis ---> n_root__eks__awsiamrolethis_n["empty!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamrolepolicyattachmentadditional["aws_iam_role_policy_attachment.additional"]:::tf-resource
  r_root__eks__awsiamrolepolicyattachmentadditional ---> n_root__eks__awsiamrolepolicyattachmentadditional_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamrolepolicyattachmentclusterencryption["aws_iam_role_policy_attachment.cluster_encryption"]:::tf-resource
  r_root__eks__awsiamrolepolicyattachmentclusterencryption ---> n_root__eks__awsiamrolepolicyattachmentclusterencryption_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamrolepolicyattachmentcustom["aws_iam_role_policy_attachment.custom"]:::tf-resource
  r_root__eks__awsiamrolepolicyattachmentcustom ---> n_root__eks__awsiamrolepolicyattachmentcustom_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamrolepolicyattachmenteksauto["aws_iam_role_policy_attachment.eks_auto"]:::tf-resource
  r_root__eks__awsiamrolepolicyattachmenteksauto ---> n_root__eks__awsiamrolepolicyattachmenteksauto_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamrolepolicyattachmenteksautoadditional["aws_iam_role_policy_attachment.eks_auto_additional"]:::tf-resource
  r_root__eks__awsiamrolepolicyattachmenteksautoadditional ---> n_root__eks__awsiamrolepolicyattachmenteksautoadditional_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awsiamrolepolicyattachmentthis["aws_iam_role_policy_attachment.this"]:::tf-resource
  r_root__eks__awsiamrolepolicyattachmentthis ---> n_root__eks__awsiamrolepolicyattachmentthis_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awssecuritygroupcluster["aws_security_group.cluster"]:::tf-resource
  r_root__eks__awssecuritygroupcluster ---> n_root__eks__awssecuritygroupcluster_n["empty!"]:::tf-name
  m_root__eks ---> r_root__eks__awssecuritygroupnode["aws_security_group.node"]:::tf-resource
  r_root__eks__awssecuritygroupnode ---> n_root__eks__awssecuritygroupnode_n["empty!"]:::tf-name
  m_root__eks ---> r_root__eks__awssecuritygrouprulecluster["aws_security_group_rule.cluster"]:::tf-resource
  r_root__eks__awssecuritygrouprulecluster ---> n_root__eks__awssecuritygrouprulecluster_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__awssecuritygrouprulenode["aws_security_group_rule.node"]:::tf-resource
  r_root__eks__awssecuritygrouprulenode ---> n_root__eks__awssecuritygrouprulenode_n["no-attr!"]:::tf-name
  m_root__eks ---> r_root__eks__timesleepthis["time_sleep.this"]:::tf-resource
  r_root__eks__timesleepthis ---> n_root__eks__timesleepthis_n["no-attr!"]:::tf-name
  p_root --> m_root__root__eks__eksmanagednodegroup["module.eks<br>terraform-aws-modules/eks/aws(at)21.3.1<br><b>/</b><br>module.eks_managed_node_group<br>./modules/eks-managed-node-group"]:::tf-int-mod
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awseksnodegroupthis["aws_eks_node_group.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awseksnodegroupthis ---> n_root__root__eks__eksmanagednodegroup__awseksnodegroupthis_n["no-attr!"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awsiamrolethis["aws_iam_role.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awsiamrolethis ---> n_root__root__eks__eksmanagednodegroup__awsiamrolethis_n["empty!"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awsiamrolepolicythis["aws_iam_role_policy.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awsiamrolepolicythis ---> n_root__root__eks__eksmanagednodegroup__awsiamrolepolicythis_n["empty!"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awsiamrolepolicyattachmentadditional["aws_iam_role_policy_attachment.additional"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awsiamrolepolicyattachmentadditional ---> n_root__root__eks__eksmanagednodegroup__awsiamrolepolicyattachmentadditional_n["no-attr!"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awsiamrolepolicyattachmentthis["aws_iam_role_policy_attachment.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awsiamrolepolicyattachmentthis ---> n_root__root__eks__eksmanagednodegroup__awsiamrolepolicyattachmentthis_n["no-attr!"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awslaunchtemplatethis["aws_launch_template.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awslaunchtemplatethis ---> n_root__root__eks__eksmanagednodegroup__awslaunchtemplatethis_n["empty!"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awsplacementgroupthis["aws_placement_group.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awsplacementgroupthis ---> n_root__root__eks__eksmanagednodegroup__awsplacementgroupthis_n["#34;${var.cluster_name}-${var.name}#34;"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awssecuritygroupthis["aws_security_group.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awssecuritygroupthis ---> n_root__root__eks__eksmanagednodegroup__awssecuritygroupthis_n["empty!"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awsvpcsecuritygroupegressrulethis["aws_vpc_security_group_egress_rule.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awsvpcsecuritygroupegressrulethis ---> n_root__root__eks__eksmanagednodegroup__awsvpcsecuritygroupegressrulethis_n["no-attr!"]:::tf-name
  m_root__root__eks__eksmanagednodegroup ---> r_root__root__eks__eksmanagednodegroup__awsvpcsecuritygroupingressrulethis["aws_vpc_security_group_ingress_rule.this"]:::tf-resource
  r_root__root__eks__eksmanagednodegroup__awsvpcsecuritygroupingressrulethis ---> n_root__root__eks__eksmanagednodegroup__awsvpcsecuritygroupingressrulethis_n["no-attr!"]:::tf-name
  p_root --> m_root__root__root__eks__eksmanagednodegroup__userdata["module.eks<br>terraform-aws-modules/eks/aws(at)21.3.1<br><b>/</b><br>module.eks_managed_node_group<br>./modules/eks-managed-node-group<br><b>/</b><br>module.user_data<br>../_user_data"]:::tf-int-mod
  m_root__root__root__eks__eksmanagednodegroup__userdata ---> r_root__root__root__eks__eksmanagednodegroup__userdata__nullresourcevalidateclusterservicecidr["null_resource.validate_cluster_service_cidr"]:::tf-resource
  r_root__root__root__eks__eksmanagednodegroup__userdata__nullresourcevalidateclusterservicecidr ---> n_root__root__root__eks__eksmanagednodegroup__userdata__nullresourcevalidateclusterservicecidr_n["no-attr!"]:::tf-name
  p_root --> m_root__root__eks__fargateprofile["module.eks<br>terraform-aws-modules/eks/aws(at)21.3.1<br><b>/</b><br>module.fargate_profile<br>./modules/fargate-profile"]:::tf-int-mod
  m_root__root__eks__fargateprofile ---> r_root__root__eks__fargateprofile__awseksfargateprofilethis["aws_eks_fargate_profile.this"]:::tf-resource
  r_root__root__eks__fargateprofile__awseksfargateprofilethis ---> n_root__root__eks__fargateprofile__awseksfargateprofilethis_n["no-attr!"]:::tf-name
  m_root__root__eks__fargateprofile ---> r_root__root__eks__fargateprofile__awsiamrolethis["aws_iam_role.this"]:::tf-resource
  r_root__root__eks__fargateprofile__awsiamrolethis ---> n_root__root__eks__fargateprofile__awsiamrolethis_n["empty!"]:::tf-name
  m_root__root__eks__fargateprofile ---> r_root__root__eks__fargateprofile__awsiamrolepolicythis["aws_iam_role_policy.this"]:::tf-resource
  r_root__root__eks__fargateprofile__awsiamrolepolicythis ---> n_root__root__eks__fargateprofile__awsiamrolepolicythis_n["empty!"]:::tf-name
  m_root__root__eks__fargateprofile ---> r_root__root__eks__fargateprofile__awsiamrolepolicyattachmentadditional["aws_iam_role_policy_attachment.additional"]:::tf-resource
  r_root__root__eks__fargateprofile__awsiamrolepolicyattachmentadditional ---> n_root__root__eks__fargateprofile__awsiamrolepolicyattachmentadditional_n["no-attr!"]:::tf-name
  m_root__root__eks__fargateprofile ---> r_root__root__eks__fargateprofile__awsiamrolepolicyattachmentthis["aws_iam_role_policy_attachment.this"]:::tf-resource
  r_root__root__eks__fargateprofile__awsiamrolepolicyattachmentthis ---> n_root__root__eks__fargateprofile__awsiamrolepolicyattachmentthis_n["no-attr!"]:::tf-name
  p_root --> m_root__root__eks__kms["module.eks<br>terraform-aws-modules/eks/aws(at)21.3.1<br><b>/</b><br>module.kms<br>terraform-aws-modules/kms/aws(at)4.0.0"]:::tf-int-mod
  m_root__root__eks__kms ---> r_root__root__eks__kms__awskmsaliasthis["aws_kms_alias.this"]:::tf-resource
  r_root__root__eks__kms__awskmsaliasthis ---> n_root__root__eks__kms__awskmsaliasthis_n["empty!"]:::tf-name
  m_root__root__eks__kms ---> r_root__root__eks__kms__awskmsexternalkeythis["aws_kms_external_key.this"]:::tf-resource
  r_root__root__eks__kms__awskmsexternalkeythis ---> n_root__root__eks__kms__awskmsexternalkeythis_n["no-attr!"]:::tf-name
  m_root__root__eks__kms ---> r_root__root__eks__kms__awskmsgrantthis["aws_kms_grant.this"]:::tf-resource
  r_root__root__eks__kms__awskmsgrantthis ---> n_root__root__eks__kms__awskmsgrantthis_n["empty!"]:::tf-name
  m_root__root__eks__kms ---> r_root__root__eks__kms__awskmskeythis["aws_kms_key.this"]:::tf-resource
  r_root__root__eks__kms__awskmskeythis ---> n_root__root__eks__kms__awskmskeythis_n["no-attr!"]:::tf-name
  m_root__root__eks__kms ---> r_root__root__eks__kms__awskmsreplicaexternalkeythis["aws_kms_replica_external_key.this"]:::tf-resource
  r_root__root__eks__kms__awskmsreplicaexternalkeythis ---> n_root__root__eks__kms__awskmsreplicaexternalkeythis_n["no-attr!"]:::tf-name
  m_root__root__eks__kms ---> r_root__root__eks__kms__awskmsreplicakeythis["aws_kms_replica_key.this"]:::tf-resource
  r_root__root__eks__kms__awskmsreplicakeythis ---> n_root__root__eks__kms__awskmsreplicakeythis_n["no-attr!"]:::tf-name
  p_root --> m_root__root__eks__selfmanagednodegroup["module.eks<br>terraform-aws-modules/eks/aws(at)21.3.1<br><b>/</b><br>module.self_managed_node_group<br>./modules/self-managed-node-group"]:::tf-int-mod
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsautoscalinggroupthis["aws_autoscaling_group.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsautoscalinggroupthis ---> n_root__root__eks__selfmanagednodegroup__awsautoscalinggroupthis_n["empty!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awseksaccessentrythis["aws_eks_access_entry.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awseksaccessentrythis ---> n_root__root__eks__selfmanagednodegroup__awseksaccessentrythis_n["no-attr!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsiaminstanceprofilethis["aws_iam_instance_profile.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsiaminstanceprofilethis ---> n_root__root__eks__selfmanagednodegroup__awsiaminstanceprofilethis_n["empty!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsiamrolethis["aws_iam_role.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsiamrolethis ---> n_root__root__eks__selfmanagednodegroup__awsiamrolethis_n["empty!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsiamrolepolicythis["aws_iam_role_policy.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsiamrolepolicythis ---> n_root__root__eks__selfmanagednodegroup__awsiamrolepolicythis_n["empty!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsiamrolepolicyattachmentadditional["aws_iam_role_policy_attachment.additional"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsiamrolepolicyattachmentadditional ---> n_root__root__eks__selfmanagednodegroup__awsiamrolepolicyattachmentadditional_n["no-attr!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsiamrolepolicyattachmentthis["aws_iam_role_policy_attachment.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsiamrolepolicyattachmentthis ---> n_root__root__eks__selfmanagednodegroup__awsiamrolepolicyattachmentthis_n["no-attr!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awslaunchtemplatethis["aws_launch_template.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awslaunchtemplatethis ---> n_root__root__eks__selfmanagednodegroup__awslaunchtemplatethis_n["empty!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsplacementgroupthis["aws_placement_group.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsplacementgroupthis ---> n_root__root__eks__selfmanagednodegroup__awsplacementgroupthis_n["#34;${var.cluster_name}-${var.name}#34;"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awssecuritygroupthis["aws_security_group.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awssecuritygroupthis ---> n_root__root__eks__selfmanagednodegroup__awssecuritygroupthis_n["empty!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsvpcsecuritygroupegressrulethis["aws_vpc_security_group_egress_rule.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsvpcsecuritygroupegressrulethis ---> n_root__root__eks__selfmanagednodegroup__awsvpcsecuritygroupegressrulethis_n["no-attr!"]:::tf-name
  m_root__root__eks__selfmanagednodegroup ---> r_root__root__eks__selfmanagednodegroup__awsvpcsecuritygroupingressrulethis["aws_vpc_security_group_ingress_rule.this"]:::tf-resource
  r_root__root__eks__selfmanagednodegroup__awsvpcsecuritygroupingressrulethis ---> n_root__root__eks__selfmanagednodegroup__awsvpcsecuritygroupingressrulethis_n["no-attr!"]:::tf-name
  p_root --> m_root__root__root__eks__selfmanagednodegroup__userdata["module.eks<br>terraform-aws-modules/eks/aws(at)21.3.1<br><b>/</b><br>module.self_managed_node_group<br>./modules/self-managed-node-group<br><b>/</b><br>module.user_data<br>../_user_data"]:::tf-int-mod
  m_root__root__root__eks__selfmanagednodegroup__userdata ---> r_root__root__root__eks__selfmanagednodegroup__userdata__nullresourcevalidateclusterservicecidr["null_resource.validate_cluster_service_cidr"]:::tf-resource
  r_root__root__root__eks__selfmanagednodegroup__userdata__nullresourcevalidateclusterservicecidr ---> n_root__root__root__eks__selfmanagednodegroup__userdata__nullresourcevalidateclusterservicecidr_n["no-attr!"]:::tf-name
  p_root --> m_root__elasticache["module.elasticache<br>terraform-aws-modules/elasticache/aws//modules/serverless-cache(at)"]:::tf-int-mod
  m_root__elasticache ---> r_root__elasticache__awselasticacheserverlesscachethis["aws_elasticache_serverless_cache.this"]:::tf-resource
  r_root__elasticache__awselasticacheserverlesscachethis ---> n_root__elasticache__awselasticacheserverlesscachethis_n["var.cache_name"]:::tf-name
  p_root --> m_root__iamaccount["module.iam_account<br>terraform-aws-modules/iam/aws//modules/iam-account(at)"]:::tf-int-mod
  m_root__iamaccount ---> r_root__iamaccount__awsiamaccountaliasthis["aws_iam_account_alias.this"]:::tf-resource
  r_root__iamaccount__awsiamaccountaliasthis ---> n_root__iamaccount__awsiamaccountaliasthis_n["no-attr!"]:::tf-name
  m_root__iamaccount ---> r_root__iamaccount__awsiamaccountpasswordpolicythis["aws_iam_account_password_policy.this"]:::tf-resource
  r_root__iamaccount__awsiamaccountpasswordpolicythis ---> n_root__iamaccount__awsiamaccountpasswordpolicythis_n["no-attr!"]:::tf-name
  p_root --> m_root__mod11["module.mod1-1<br>external-module-1(at)0.0.1"]:::tf-int-mod
  m_root__mod11 ---> r_root__mod11__nevermindnevermind1["nevermind.nevermind-1"]:::tf-resource
  r_root__mod11__nevermindnevermind1 ---> n_root__mod11__nevermindnevermind1_n["#34;name-nevermind-1#34;"]:::tf-name
  m_root__mod11 ---> r_root__mod11__typeextmod11["type.extmod-1-1"]:::tf-resource
  r_root__mod11__typeextmod11 ---> n_root__mod11__typeextmod11_n["#34;name-extmod-1-1#34;"]:::tf-name
  m_root__mod11 ---> r_root__mod11__typeextmod12["type.extmod-1-2<br>*for_each = var.value6*"]:::tf-resource
  r_root__mod11__typeextmod12 ---> n_root__mod11__typeextmod12_n:::tf-name@{ shape: procs, label: "#34;name-extmod-1-2#34;"}
  p_root --> m_root__root__mod11__vpc["module.mod1-1<br>external-module-1(at)0.0.1<br><b>/</b><br>module.vpc<br>terraform-aws-modules/vpc/aws(at)"]:::tf-int-mod
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awscloudwatchloggroupflowlog["aws_cloudwatch_log_group.flow_log"]:::tf-resource
  r_root__root__mod11__vpc__awscloudwatchloggroupflowlog ---> n_root__root__mod11__vpc__awscloudwatchloggroupflowlog_n["#34;${var.flow_log_cloudwatch_log_group_name_prefix}${local.flow_log_cloudwatch_log_group_name_suffix}#34;"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awscustomergatewaythis["aws_customer_gateway.this<br>*for_each = var.customer_gateways*"]:::tf-resource
  r_root__root__mod11__vpc__awscustomergatewaythis ---> n_root__root__mod11__vpc__awscustomergatewaythis_n:::tf-name@{ shape: procs, label: "no-attr!"}
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsdbsubnetgroupdatabase["aws_db_subnet_group.database"]:::tf-resource
  r_root__root__mod11__vpc__awsdbsubnetgroupdatabase ---> n_root__root__mod11__vpc__awsdbsubnetgroupdatabase_n["empty!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsdefaultnetworkaclthis["aws_default_network_acl.this"]:::tf-resource
  r_root__root__mod11__vpc__awsdefaultnetworkaclthis ---> n_root__root__mod11__vpc__awsdefaultnetworkaclthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsdefaultroutetabledefault["aws_default_route_table.default"]:::tf-resource
  r_root__root__mod11__vpc__awsdefaultroutetabledefault ---> n_root__root__mod11__vpc__awsdefaultroutetabledefault_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsdefaultsecuritygroupthis["aws_default_security_group.this"]:::tf-resource
  r_root__root__mod11__vpc__awsdefaultsecuritygroupthis ---> n_root__root__mod11__vpc__awsdefaultsecuritygroupthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsdefaultvpcthis["aws_default_vpc.this"]:::tf-resource
  r_root__root__mod11__vpc__awsdefaultvpcthis ---> n_root__root__mod11__vpc__awsdefaultvpcthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsegressonlyinternetgatewaythis["aws_egress_only_internet_gateway.this"]:::tf-resource
  r_root__root__mod11__vpc__awsegressonlyinternetgatewaythis ---> n_root__root__mod11__vpc__awsegressonlyinternetgatewaythis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awseipnat["aws_eip.nat"]:::tf-resource
  r_root__root__mod11__vpc__awseipnat ---> n_root__root__mod11__vpc__awseipnat_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awselasticachesubnetgroupelasticache["aws_elasticache_subnet_group.elasticache"]:::tf-resource
  r_root__root__mod11__vpc__awselasticachesubnetgroupelasticache ---> n_root__root__mod11__vpc__awselasticachesubnetgroupelasticache_n["empty!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsflowlogthis["aws_flow_log.this"]:::tf-resource
  r_root__root__mod11__vpc__awsflowlogthis ---> n_root__root__mod11__vpc__awsflowlogthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsiampolicyvpcflowlogcloudwatch["aws_iam_policy.vpc_flow_log_cloudwatch"]:::tf-resource
  r_root__root__mod11__vpc__awsiampolicyvpcflowlogcloudwatch ---> n_root__root__mod11__vpc__awsiampolicyvpcflowlogcloudwatch_n["empty!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsiamrolevpcflowlogcloudwatch["aws_iam_role.vpc_flow_log_cloudwatch"]:::tf-resource
  r_root__root__mod11__vpc__awsiamrolevpcflowlogcloudwatch ---> n_root__root__mod11__vpc__awsiamrolevpcflowlogcloudwatch_n["empty!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsiamrolepolicyattachmentvpcflowlogcloudwatch["aws_iam_role_policy_attachment.vpc_flow_log_cloudwatch"]:::tf-resource
  r_root__root__mod11__vpc__awsiamrolepolicyattachmentvpcflowlogcloudwatch ---> n_root__root__mod11__vpc__awsiamrolepolicyattachmentvpcflowlogcloudwatch_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsinternetgatewaythis["aws_internet_gateway.this"]:::tf-resource
  r_root__root__mod11__vpc__awsinternetgatewaythis ---> n_root__root__mod11__vpc__awsinternetgatewaythis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnatgatewaythis["aws_nat_gateway.this"]:::tf-resource
  r_root__root__mod11__vpc__awsnatgatewaythis ---> n_root__root__mod11__vpc__awsnatgatewaythis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkacldatabase["aws_network_acl.database"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkacldatabase ---> n_root__root__mod11__vpc__awsnetworkacldatabase_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclelasticache["aws_network_acl.elasticache"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclelasticache ---> n_root__root__mod11__vpc__awsnetworkaclelasticache_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclintra["aws_network_acl.intra"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclintra ---> n_root__root__mod11__vpc__awsnetworkaclintra_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkacloutpost["aws_network_acl.outpost"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkacloutpost ---> n_root__root__mod11__vpc__awsnetworkacloutpost_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclprivate["aws_network_acl.private"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclprivate ---> n_root__root__mod11__vpc__awsnetworkaclprivate_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclpublic["aws_network_acl.public"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclpublic ---> n_root__root__mod11__vpc__awsnetworkaclpublic_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclredshift["aws_network_acl.redshift"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclredshift ---> n_root__root__mod11__vpc__awsnetworkaclredshift_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruledatabaseinbound["aws_network_acl_rule.database_inbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruledatabaseinbound ---> n_root__root__mod11__vpc__awsnetworkaclruledatabaseinbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruledatabaseoutbound["aws_network_acl_rule.database_outbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruledatabaseoutbound ---> n_root__root__mod11__vpc__awsnetworkaclruledatabaseoutbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleelasticacheinbound["aws_network_acl_rule.elasticache_inbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleelasticacheinbound ---> n_root__root__mod11__vpc__awsnetworkaclruleelasticacheinbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleelasticacheoutbound["aws_network_acl_rule.elasticache_outbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleelasticacheoutbound ---> n_root__root__mod11__vpc__awsnetworkaclruleelasticacheoutbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleintrainbound["aws_network_acl_rule.intra_inbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleintrainbound ---> n_root__root__mod11__vpc__awsnetworkaclruleintrainbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleintraoutbound["aws_network_acl_rule.intra_outbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleintraoutbound ---> n_root__root__mod11__vpc__awsnetworkaclruleintraoutbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleoutpostinbound["aws_network_acl_rule.outpost_inbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleoutpostinbound ---> n_root__root__mod11__vpc__awsnetworkaclruleoutpostinbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleoutpostoutbound["aws_network_acl_rule.outpost_outbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleoutpostoutbound ---> n_root__root__mod11__vpc__awsnetworkaclruleoutpostoutbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleprivateinbound["aws_network_acl_rule.private_inbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleprivateinbound ---> n_root__root__mod11__vpc__awsnetworkaclruleprivateinbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleprivateoutbound["aws_network_acl_rule.private_outbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleprivateoutbound ---> n_root__root__mod11__vpc__awsnetworkaclruleprivateoutbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclrulepublicinbound["aws_network_acl_rule.public_inbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclrulepublicinbound ---> n_root__root__mod11__vpc__awsnetworkaclrulepublicinbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclrulepublicoutbound["aws_network_acl_rule.public_outbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclrulepublicoutbound ---> n_root__root__mod11__vpc__awsnetworkaclrulepublicoutbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleredshiftinbound["aws_network_acl_rule.redshift_inbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleredshiftinbound ---> n_root__root__mod11__vpc__awsnetworkaclruleredshiftinbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsnetworkaclruleredshiftoutbound["aws_network_acl_rule.redshift_outbound"]:::tf-resource
  r_root__root__mod11__vpc__awsnetworkaclruleredshiftoutbound ---> n_root__root__mod11__vpc__awsnetworkaclruleredshiftoutbound_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsredshiftsubnetgroupredshift["aws_redshift_subnet_group.redshift"]:::tf-resource
  r_root__root__mod11__vpc__awsredshiftsubnetgroupredshift ---> n_root__root__mod11__vpc__awsredshiftsubnetgroupredshift_n["empty!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutedatabasedns64natgateway["aws_route.database_dns64_nat_gateway"]:::tf-resource
  r_root__root__mod11__vpc__awsroutedatabasedns64natgateway ---> n_root__root__mod11__vpc__awsroutedatabasedns64natgateway_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutedatabaseinternetgateway["aws_route.database_internet_gateway"]:::tf-resource
  r_root__root__mod11__vpc__awsroutedatabaseinternetgateway ---> n_root__root__mod11__vpc__awsroutedatabaseinternetgateway_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutedatabaseipv6egress["aws_route.database_ipv6_egress"]:::tf-resource
  r_root__root__mod11__vpc__awsroutedatabaseipv6egress ---> n_root__root__mod11__vpc__awsroutedatabaseipv6egress_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutedatabasenatgateway["aws_route.database_nat_gateway"]:::tf-resource
  r_root__root__mod11__vpc__awsroutedatabasenatgateway ---> n_root__root__mod11__vpc__awsroutedatabasenatgateway_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsrouteprivatedns64natgateway["aws_route.private_dns64_nat_gateway"]:::tf-resource
  r_root__root__mod11__vpc__awsrouteprivatedns64natgateway ---> n_root__root__mod11__vpc__awsrouteprivatedns64natgateway_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsrouteprivateipv6egress["aws_route.private_ipv6_egress"]:::tf-resource
  r_root__root__mod11__vpc__awsrouteprivateipv6egress ---> n_root__root__mod11__vpc__awsrouteprivateipv6egress_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsrouteprivatenatgateway["aws_route.private_nat_gateway"]:::tf-resource
  r_root__root__mod11__vpc__awsrouteprivatenatgateway ---> n_root__root__mod11__vpc__awsrouteprivatenatgateway_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutepublicinternetgateway["aws_route.public_internet_gateway"]:::tf-resource
  r_root__root__mod11__vpc__awsroutepublicinternetgateway ---> n_root__root__mod11__vpc__awsroutepublicinternetgateway_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutepublicinternetgatewayipv6["aws_route.public_internet_gateway_ipv6"]:::tf-resource
  r_root__root__mod11__vpc__awsroutepublicinternetgatewayipv6 ---> n_root__root__mod11__vpc__awsroutepublicinternetgatewayipv6_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetabledatabase["aws_route_table.database"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetabledatabase ---> n_root__root__mod11__vpc__awsroutetabledatabase_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableelasticache["aws_route_table.elasticache"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableelasticache ---> n_root__root__mod11__vpc__awsroutetableelasticache_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableintra["aws_route_table.intra"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableintra ---> n_root__root__mod11__vpc__awsroutetableintra_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableprivate["aws_route_table.private"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableprivate ---> n_root__root__mod11__vpc__awsroutetableprivate_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetablepublic["aws_route_table.public"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetablepublic ---> n_root__root__mod11__vpc__awsroutetablepublic_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableredshift["aws_route_table.redshift"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableredshift ---> n_root__root__mod11__vpc__awsroutetableredshift_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableassociationdatabase["aws_route_table_association.database"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableassociationdatabase ---> n_root__root__mod11__vpc__awsroutetableassociationdatabase_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableassociationelasticache["aws_route_table_association.elasticache"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableassociationelasticache ---> n_root__root__mod11__vpc__awsroutetableassociationelasticache_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableassociationintra["aws_route_table_association.intra"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableassociationintra ---> n_root__root__mod11__vpc__awsroutetableassociationintra_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableassociationoutpost["aws_route_table_association.outpost"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableassociationoutpost ---> n_root__root__mod11__vpc__awsroutetableassociationoutpost_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableassociationprivate["aws_route_table_association.private"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableassociationprivate ---> n_root__root__mod11__vpc__awsroutetableassociationprivate_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableassociationpublic["aws_route_table_association.public"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableassociationpublic ---> n_root__root__mod11__vpc__awsroutetableassociationpublic_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableassociationredshift["aws_route_table_association.redshift"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableassociationredshift ---> n_root__root__mod11__vpc__awsroutetableassociationredshift_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsroutetableassociationredshiftpublic["aws_route_table_association.redshift_public"]:::tf-resource
  r_root__root__mod11__vpc__awsroutetableassociationredshiftpublic ---> n_root__root__mod11__vpc__awsroutetableassociationredshiftpublic_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awssubnetdatabase["aws_subnet.database"]:::tf-resource
  r_root__root__mod11__vpc__awssubnetdatabase ---> n_root__root__mod11__vpc__awssubnetdatabase_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awssubnetelasticache["aws_subnet.elasticache"]:::tf-resource
  r_root__root__mod11__vpc__awssubnetelasticache ---> n_root__root__mod11__vpc__awssubnetelasticache_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awssubnetintra["aws_subnet.intra"]:::tf-resource
  r_root__root__mod11__vpc__awssubnetintra ---> n_root__root__mod11__vpc__awssubnetintra_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awssubnetoutpost["aws_subnet.outpost"]:::tf-resource
  r_root__root__mod11__vpc__awssubnetoutpost ---> n_root__root__mod11__vpc__awssubnetoutpost_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awssubnetprivate["aws_subnet.private"]:::tf-resource
  r_root__root__mod11__vpc__awssubnetprivate ---> n_root__root__mod11__vpc__awssubnetprivate_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awssubnetpublic["aws_subnet.public"]:::tf-resource
  r_root__root__mod11__vpc__awssubnetpublic ---> n_root__root__mod11__vpc__awssubnetpublic_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awssubnetredshift["aws_subnet.redshift"]:::tf-resource
  r_root__root__mod11__vpc__awssubnetredshift ---> n_root__root__mod11__vpc__awssubnetredshift_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpcthis["aws_vpc.this"]:::tf-resource
  r_root__root__mod11__vpc__awsvpcthis ---> n_root__root__mod11__vpc__awsvpcthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpcblockpublicaccessexclusionthis["aws_vpc_block_public_access_exclusion.this"]:::tf-resource
  r_root__root__mod11__vpc__awsvpcblockpublicaccessexclusionthis ---> n_root__root__mod11__vpc__awsvpcblockpublicaccessexclusionthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpcblockpublicaccessoptionsthis["aws_vpc_block_public_access_options.this"]:::tf-resource
  r_root__root__mod11__vpc__awsvpcblockpublicaccessoptionsthis ---> n_root__root__mod11__vpc__awsvpcblockpublicaccessoptionsthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpcdhcpoptionsthis["aws_vpc_dhcp_options.this"]:::tf-resource
  r_root__root__mod11__vpc__awsvpcdhcpoptionsthis ---> n_root__root__mod11__vpc__awsvpcdhcpoptionsthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpcdhcpoptionsassociationthis["aws_vpc_dhcp_options_association.this"]:::tf-resource
  r_root__root__mod11__vpc__awsvpcdhcpoptionsassociationthis ---> n_root__root__mod11__vpc__awsvpcdhcpoptionsassociationthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpcipv4cidrblockassociationthis["aws_vpc_ipv4_cidr_block_association.this"]:::tf-resource
  r_root__root__mod11__vpc__awsvpcipv4cidrblockassociationthis ---> n_root__root__mod11__vpc__awsvpcipv4cidrblockassociationthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpngatewaythis["aws_vpn_gateway.this"]:::tf-resource
  r_root__root__mod11__vpc__awsvpngatewaythis ---> n_root__root__mod11__vpc__awsvpngatewaythis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpngatewayattachmentthis["aws_vpn_gateway_attachment.this"]:::tf-resource
  r_root__root__mod11__vpc__awsvpngatewayattachmentthis ---> n_root__root__mod11__vpc__awsvpngatewayattachmentthis_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpngatewayroutepropagationintra["aws_vpn_gateway_route_propagation.intra"]:::tf-resource
  r_root__root__mod11__vpc__awsvpngatewayroutepropagationintra ---> n_root__root__mod11__vpc__awsvpngatewayroutepropagationintra_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpngatewayroutepropagationprivate["aws_vpn_gateway_route_propagation.private"]:::tf-resource
  r_root__root__mod11__vpc__awsvpngatewayroutepropagationprivate ---> n_root__root__mod11__vpc__awsvpngatewayroutepropagationprivate_n["no-attr!"]:::tf-name
  m_root__root__mod11__vpc ---> r_root__root__mod11__vpc__awsvpngatewayroutepropagationpublic["aws_vpn_gateway_route_propagation.public"]:::tf-resource
  r_root__root__mod11__vpc__awsvpngatewayroutepropagationpublic ---> n_root__root__mod11__vpc__awsvpngatewayroutepropagationpublic_n["no-attr!"]:::tf-name
  p_root --> m_root__mod21["module.mod2-1<br>external-module-2(at)0.0.1"]:::tf-int-mod
  m_root__mod21 ---> r_root__mod21__typeextmod21["type.extmod-2-1"]:::tf-resource
  r_root__mod21__typeextmod21 ---> n_root__mod21__typeextmod21_n["#34;name-extmod-2-1#34;"]:::tf-name
  m_root__mod21 ---> r_root__mod21__typeextmod22["type.extmod-2-2"]:::tf-resource
  r_root__mod21__typeextmod22 ---> n_root__mod21__typeextmod22_n["#34;name-extmod-2-2#34;"]:::tf-name
  p_root --> m_root__root__mod21__subm2["module.mod2-1<br>external-module-2(at)0.0.1<br><b>/</b><br>module.subm2<br>./subm2<br>*for_each = var.value7*"]:::tf-int-mod
  m_root__root__mod21__subm2 ---> r_root__root__mod21__subm2__typesubm21["type.subm2-1"]:::tf-resource
  r_root__root__mod21__subm2__typesubm21 ---> n_root__root__mod21__subm2__typesubm21_n:::tf-name@{ shape: procs, label: "#34;name-subm2-1#34;"}
  p_root --> m_root__mod2sub11["module.mod2sub1-1<br>external-module-2//modules/sub1(at)0.0.1"]:::tf-int-mod
  m_root__mod2sub11 ---> r_root__mod2sub11__typesubm11["type.subm1-1"]:::tf-resource
  r_root__mod2sub11__typesubm11 ---> n_root__mod2sub11__typesubm11_n["#34;name-subm1-1#34;"]:::tf-name
  p_root --> m_root__vpc["module.vpc<br>terraform-aws-modules/vpc/aws(at)"]:::tf-int-mod
  m_root__vpc ---> r_root__vpc__awscloudwatchloggroupflowlog["aws_cloudwatch_log_group.flow_log"]:::tf-resource
  r_root__vpc__awscloudwatchloggroupflowlog ---> n_root__vpc__awscloudwatchloggroupflowlog_n["#34;${var.flow_log_cloudwatch_log_group_name_prefix}${local.flow_log_cloudwatch_log_group_name_suffix}#34;"]:::tf-name
  m_root__vpc ---> r_root__vpc__awscustomergatewaythis["aws_customer_gateway.this<br>*for_each = var.customer_gateways*"]:::tf-resource
  r_root__vpc__awscustomergatewaythis ---> n_root__vpc__awscustomergatewaythis_n:::tf-name@{ shape: procs, label: "no-attr!"}
  m_root__vpc ---> r_root__vpc__awsdbsubnetgroupdatabase["aws_db_subnet_group.database"]:::tf-resource
  r_root__vpc__awsdbsubnetgroupdatabase ---> n_root__vpc__awsdbsubnetgroupdatabase_n["empty!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsdefaultnetworkaclthis["aws_default_network_acl.this"]:::tf-resource
  r_root__vpc__awsdefaultnetworkaclthis ---> n_root__vpc__awsdefaultnetworkaclthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsdefaultroutetabledefault["aws_default_route_table.default"]:::tf-resource
  r_root__vpc__awsdefaultroutetabledefault ---> n_root__vpc__awsdefaultroutetabledefault_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsdefaultsecuritygroupthis["aws_default_security_group.this"]:::tf-resource
  r_root__vpc__awsdefaultsecuritygroupthis ---> n_root__vpc__awsdefaultsecuritygroupthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsdefaultvpcthis["aws_default_vpc.this"]:::tf-resource
  r_root__vpc__awsdefaultvpcthis ---> n_root__vpc__awsdefaultvpcthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsegressonlyinternetgatewaythis["aws_egress_only_internet_gateway.this"]:::tf-resource
  r_root__vpc__awsegressonlyinternetgatewaythis ---> n_root__vpc__awsegressonlyinternetgatewaythis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awseipnat["aws_eip.nat"]:::tf-resource
  r_root__vpc__awseipnat ---> n_root__vpc__awseipnat_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awselasticachesubnetgroupelasticache["aws_elasticache_subnet_group.elasticache"]:::tf-resource
  r_root__vpc__awselasticachesubnetgroupelasticache ---> n_root__vpc__awselasticachesubnetgroupelasticache_n["empty!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsflowlogthis["aws_flow_log.this"]:::tf-resource
  r_root__vpc__awsflowlogthis ---> n_root__vpc__awsflowlogthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsiampolicyvpcflowlogcloudwatch["aws_iam_policy.vpc_flow_log_cloudwatch"]:::tf-resource
  r_root__vpc__awsiampolicyvpcflowlogcloudwatch ---> n_root__vpc__awsiampolicyvpcflowlogcloudwatch_n["empty!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsiamrolevpcflowlogcloudwatch["aws_iam_role.vpc_flow_log_cloudwatch"]:::tf-resource
  r_root__vpc__awsiamrolevpcflowlogcloudwatch ---> n_root__vpc__awsiamrolevpcflowlogcloudwatch_n["empty!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsiamrolepolicyattachmentvpcflowlogcloudwatch["aws_iam_role_policy_attachment.vpc_flow_log_cloudwatch"]:::tf-resource
  r_root__vpc__awsiamrolepolicyattachmentvpcflowlogcloudwatch ---> n_root__vpc__awsiamrolepolicyattachmentvpcflowlogcloudwatch_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsinternetgatewaythis["aws_internet_gateway.this"]:::tf-resource
  r_root__vpc__awsinternetgatewaythis ---> n_root__vpc__awsinternetgatewaythis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnatgatewaythis["aws_nat_gateway.this"]:::tf-resource
  r_root__vpc__awsnatgatewaythis ---> n_root__vpc__awsnatgatewaythis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkacldatabase["aws_network_acl.database"]:::tf-resource
  r_root__vpc__awsnetworkacldatabase ---> n_root__vpc__awsnetworkacldatabase_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclelasticache["aws_network_acl.elasticache"]:::tf-resource
  r_root__vpc__awsnetworkaclelasticache ---> n_root__vpc__awsnetworkaclelasticache_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclintra["aws_network_acl.intra"]:::tf-resource
  r_root__vpc__awsnetworkaclintra ---> n_root__vpc__awsnetworkaclintra_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkacloutpost["aws_network_acl.outpost"]:::tf-resource
  r_root__vpc__awsnetworkacloutpost ---> n_root__vpc__awsnetworkacloutpost_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclprivate["aws_network_acl.private"]:::tf-resource
  r_root__vpc__awsnetworkaclprivate ---> n_root__vpc__awsnetworkaclprivate_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclpublic["aws_network_acl.public"]:::tf-resource
  r_root__vpc__awsnetworkaclpublic ---> n_root__vpc__awsnetworkaclpublic_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclredshift["aws_network_acl.redshift"]:::tf-resource
  r_root__vpc__awsnetworkaclredshift ---> n_root__vpc__awsnetworkaclredshift_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruledatabaseinbound["aws_network_acl_rule.database_inbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruledatabaseinbound ---> n_root__vpc__awsnetworkaclruledatabaseinbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruledatabaseoutbound["aws_network_acl_rule.database_outbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruledatabaseoutbound ---> n_root__vpc__awsnetworkaclruledatabaseoutbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleelasticacheinbound["aws_network_acl_rule.elasticache_inbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleelasticacheinbound ---> n_root__vpc__awsnetworkaclruleelasticacheinbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleelasticacheoutbound["aws_network_acl_rule.elasticache_outbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleelasticacheoutbound ---> n_root__vpc__awsnetworkaclruleelasticacheoutbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleintrainbound["aws_network_acl_rule.intra_inbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleintrainbound ---> n_root__vpc__awsnetworkaclruleintrainbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleintraoutbound["aws_network_acl_rule.intra_outbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleintraoutbound ---> n_root__vpc__awsnetworkaclruleintraoutbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleoutpostinbound["aws_network_acl_rule.outpost_inbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleoutpostinbound ---> n_root__vpc__awsnetworkaclruleoutpostinbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleoutpostoutbound["aws_network_acl_rule.outpost_outbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleoutpostoutbound ---> n_root__vpc__awsnetworkaclruleoutpostoutbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleprivateinbound["aws_network_acl_rule.private_inbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleprivateinbound ---> n_root__vpc__awsnetworkaclruleprivateinbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleprivateoutbound["aws_network_acl_rule.private_outbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleprivateoutbound ---> n_root__vpc__awsnetworkaclruleprivateoutbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclrulepublicinbound["aws_network_acl_rule.public_inbound"]:::tf-resource
  r_root__vpc__awsnetworkaclrulepublicinbound ---> n_root__vpc__awsnetworkaclrulepublicinbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclrulepublicoutbound["aws_network_acl_rule.public_outbound"]:::tf-resource
  r_root__vpc__awsnetworkaclrulepublicoutbound ---> n_root__vpc__awsnetworkaclrulepublicoutbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleredshiftinbound["aws_network_acl_rule.redshift_inbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleredshiftinbound ---> n_root__vpc__awsnetworkaclruleredshiftinbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsnetworkaclruleredshiftoutbound["aws_network_acl_rule.redshift_outbound"]:::tf-resource
  r_root__vpc__awsnetworkaclruleredshiftoutbound ---> n_root__vpc__awsnetworkaclruleredshiftoutbound_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsredshiftsubnetgroupredshift["aws_redshift_subnet_group.redshift"]:::tf-resource
  r_root__vpc__awsredshiftsubnetgroupredshift ---> n_root__vpc__awsredshiftsubnetgroupredshift_n["empty!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutedatabasedns64natgateway["aws_route.database_dns64_nat_gateway"]:::tf-resource
  r_root__vpc__awsroutedatabasedns64natgateway ---> n_root__vpc__awsroutedatabasedns64natgateway_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutedatabaseinternetgateway["aws_route.database_internet_gateway"]:::tf-resource
  r_root__vpc__awsroutedatabaseinternetgateway ---> n_root__vpc__awsroutedatabaseinternetgateway_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutedatabaseipv6egress["aws_route.database_ipv6_egress"]:::tf-resource
  r_root__vpc__awsroutedatabaseipv6egress ---> n_root__vpc__awsroutedatabaseipv6egress_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutedatabasenatgateway["aws_route.database_nat_gateway"]:::tf-resource
  r_root__vpc__awsroutedatabasenatgateway ---> n_root__vpc__awsroutedatabasenatgateway_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsrouteprivatedns64natgateway["aws_route.private_dns64_nat_gateway"]:::tf-resource
  r_root__vpc__awsrouteprivatedns64natgateway ---> n_root__vpc__awsrouteprivatedns64natgateway_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsrouteprivateipv6egress["aws_route.private_ipv6_egress"]:::tf-resource
  r_root__vpc__awsrouteprivateipv6egress ---> n_root__vpc__awsrouteprivateipv6egress_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsrouteprivatenatgateway["aws_route.private_nat_gateway"]:::tf-resource
  r_root__vpc__awsrouteprivatenatgateway ---> n_root__vpc__awsrouteprivatenatgateway_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutepublicinternetgateway["aws_route.public_internet_gateway"]:::tf-resource
  r_root__vpc__awsroutepublicinternetgateway ---> n_root__vpc__awsroutepublicinternetgateway_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutepublicinternetgatewayipv6["aws_route.public_internet_gateway_ipv6"]:::tf-resource
  r_root__vpc__awsroutepublicinternetgatewayipv6 ---> n_root__vpc__awsroutepublicinternetgatewayipv6_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetabledatabase["aws_route_table.database"]:::tf-resource
  r_root__vpc__awsroutetabledatabase ---> n_root__vpc__awsroutetabledatabase_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableelasticache["aws_route_table.elasticache"]:::tf-resource
  r_root__vpc__awsroutetableelasticache ---> n_root__vpc__awsroutetableelasticache_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableintra["aws_route_table.intra"]:::tf-resource
  r_root__vpc__awsroutetableintra ---> n_root__vpc__awsroutetableintra_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableprivate["aws_route_table.private"]:::tf-resource
  r_root__vpc__awsroutetableprivate ---> n_root__vpc__awsroutetableprivate_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetablepublic["aws_route_table.public"]:::tf-resource
  r_root__vpc__awsroutetablepublic ---> n_root__vpc__awsroutetablepublic_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableredshift["aws_route_table.redshift"]:::tf-resource
  r_root__vpc__awsroutetableredshift ---> n_root__vpc__awsroutetableredshift_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableassociationdatabase["aws_route_table_association.database"]:::tf-resource
  r_root__vpc__awsroutetableassociationdatabase ---> n_root__vpc__awsroutetableassociationdatabase_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableassociationelasticache["aws_route_table_association.elasticache"]:::tf-resource
  r_root__vpc__awsroutetableassociationelasticache ---> n_root__vpc__awsroutetableassociationelasticache_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableassociationintra["aws_route_table_association.intra"]:::tf-resource
  r_root__vpc__awsroutetableassociationintra ---> n_root__vpc__awsroutetableassociationintra_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableassociationoutpost["aws_route_table_association.outpost"]:::tf-resource
  r_root__vpc__awsroutetableassociationoutpost ---> n_root__vpc__awsroutetableassociationoutpost_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableassociationprivate["aws_route_table_association.private"]:::tf-resource
  r_root__vpc__awsroutetableassociationprivate ---> n_root__vpc__awsroutetableassociationprivate_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableassociationpublic["aws_route_table_association.public"]:::tf-resource
  r_root__vpc__awsroutetableassociationpublic ---> n_root__vpc__awsroutetableassociationpublic_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableassociationredshift["aws_route_table_association.redshift"]:::tf-resource
  r_root__vpc__awsroutetableassociationredshift ---> n_root__vpc__awsroutetableassociationredshift_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsroutetableassociationredshiftpublic["aws_route_table_association.redshift_public"]:::tf-resource
  r_root__vpc__awsroutetableassociationredshiftpublic ---> n_root__vpc__awsroutetableassociationredshiftpublic_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awssubnetdatabase["aws_subnet.database"]:::tf-resource
  r_root__vpc__awssubnetdatabase ---> n_root__vpc__awssubnetdatabase_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awssubnetelasticache["aws_subnet.elasticache"]:::tf-resource
  r_root__vpc__awssubnetelasticache ---> n_root__vpc__awssubnetelasticache_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awssubnetintra["aws_subnet.intra"]:::tf-resource
  r_root__vpc__awssubnetintra ---> n_root__vpc__awssubnetintra_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awssubnetoutpost["aws_subnet.outpost"]:::tf-resource
  r_root__vpc__awssubnetoutpost ---> n_root__vpc__awssubnetoutpost_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awssubnetprivate["aws_subnet.private"]:::tf-resource
  r_root__vpc__awssubnetprivate ---> n_root__vpc__awssubnetprivate_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awssubnetpublic["aws_subnet.public"]:::tf-resource
  r_root__vpc__awssubnetpublic ---> n_root__vpc__awssubnetpublic_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awssubnetredshift["aws_subnet.redshift"]:::tf-resource
  r_root__vpc__awssubnetredshift ---> n_root__vpc__awssubnetredshift_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpcthis["aws_vpc.this"]:::tf-resource
  r_root__vpc__awsvpcthis ---> n_root__vpc__awsvpcthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpcblockpublicaccessexclusionthis["aws_vpc_block_public_access_exclusion.this"]:::tf-resource
  r_root__vpc__awsvpcblockpublicaccessexclusionthis ---> n_root__vpc__awsvpcblockpublicaccessexclusionthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpcblockpublicaccessoptionsthis["aws_vpc_block_public_access_options.this"]:::tf-resource
  r_root__vpc__awsvpcblockpublicaccessoptionsthis ---> n_root__vpc__awsvpcblockpublicaccessoptionsthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpcdhcpoptionsthis["aws_vpc_dhcp_options.this"]:::tf-resource
  r_root__vpc__awsvpcdhcpoptionsthis ---> n_root__vpc__awsvpcdhcpoptionsthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpcdhcpoptionsassociationthis["aws_vpc_dhcp_options_association.this"]:::tf-resource
  r_root__vpc__awsvpcdhcpoptionsassociationthis ---> n_root__vpc__awsvpcdhcpoptionsassociationthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpcipv4cidrblockassociationthis["aws_vpc_ipv4_cidr_block_association.this"]:::tf-resource
  r_root__vpc__awsvpcipv4cidrblockassociationthis ---> n_root__vpc__awsvpcipv4cidrblockassociationthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpngatewaythis["aws_vpn_gateway.this"]:::tf-resource
  r_root__vpc__awsvpngatewaythis ---> n_root__vpc__awsvpngatewaythis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpngatewayattachmentthis["aws_vpn_gateway_attachment.this"]:::tf-resource
  r_root__vpc__awsvpngatewayattachmentthis ---> n_root__vpc__awsvpngatewayattachmentthis_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpngatewayroutepropagationintra["aws_vpn_gateway_route_propagation.intra"]:::tf-resource
  r_root__vpc__awsvpngatewayroutepropagationintra ---> n_root__vpc__awsvpngatewayroutepropagationintra_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpngatewayroutepropagationprivate["aws_vpn_gateway_route_propagation.private"]:::tf-resource
  r_root__vpc__awsvpngatewayroutepropagationprivate ---> n_root__vpc__awsvpngatewayroutepropagationprivate_n["no-attr!"]:::tf-name
  m_root__vpc ---> r_root__vpc__awsvpngatewayroutepropagationpublic["aws_vpn_gateway_route_propagation.public"]:::tf-resource
  r_root__vpc__awsvpngatewayroutepropagationpublic ---> n_root__vpc__awsvpngatewayroutepropagationpublic_n["no-attr!"]:::tf-name
